#cloud-config

package_upgrade: true

packages:
  - python3
  - python3-pip

write_files:
  - content: |
      [Unit]
      Description=TCP Server Service
      After=network.target

      [Service]
      Type=simple
      User=root
      WorkingDirectory=/root
      ExecStart=/usr/bin/python3 /root/tcp_server.py --webhook-url <WEBHOOK_URL> --port <PORT> --escape-char <ESCAPE_CHAR>
      StandardOutput=syslog
      StandardError=syslog
      SyslogIdentifier=tcp_server
      StandardOutput=file:/var/log/tcp_server.log
      Restart=always
      RestartSec=5
      StartLimitInterval=0

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/tcp_server.service

runcmd:
  - curl -sSL -o /root/tcp_server.py <SCRIPT_URL>
  - pip3 install requests
  - systemctl daemon-reload
  - systemctl enable tcp_server.service
  - systemctl start tcp_server.service
